name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: rest/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
      - name: Run e2e tests
        run: npm run test:e2e
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rest
    concurrency: heroku-deploy
    needs: backend
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bead-blog-rest" #Must be unique in Heroku
          heroku_email: "dorinagy06@gmail.com"
          appdir: "rest"
          branch: "main"
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: ui/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test:ci
  frontend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    concurrency: heroku-deploy
    needs: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bead-blog-ui" #Must be unique in Heroku
          heroku_email: "dorinagy06@gmail.com"
          appdir: "ui"
          branch: "main"