name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: rest/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
      - name: Run e2e tests
        run: npm run test:e2e
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: ui/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test:ci